openapi: "3.0.1"
info:
  version: 1.0.0
  title: go_echo
  license:
    name: R5437198
servers:
  - url: http://localhost:80
paths:
  /:
    get:
      operationId: getHealthCheck
      tags:
        - health_check
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultResponse'
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    DefaultResponse:
      required:
        - result
      properties:
        result:
          type: string
          default: success
    ErrorResponse:
      properties:
        message:
          type: string
          example: internal server error
        code:
          type: string
          example: 404