openapi: "3.0.1"
info:
  version: 1.0.0
  title: go_echo
  license:
    name: R5437198
servers:
  - url: http://localhost:80
paths:
  /:
    get:
      operationId: getHealthCheck
      description: ヘルスチェック
      tags:
        - health_check
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultResponse'
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /sex-types:
    get:
      operationId: getSexTypes
      description: 性別のマスターデータ
      tags:
        - sex_type
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#/components/schemas/SexTypeResponse"
        '404':
          description: not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    DefaultResponse:
      required:
        - result
      properties:
        result:
          type: string
          default: success
    ErrorResponse:
      required:
        - message
        - code
      properties:
        message:
          type: string
          example: internal server error
        code:
          type: string
          example: 404
    SexTypeResponse:
      required:
        - id
        - value
        - created_at
        - updated_at
      properties:
        id:
          type: string
        value:
          type: string
        created_at:
          type: string
        updated_at:
          type: string
