version: "3.4"

services:
  rest:
    container_name: rest
    build:
      context: ./
      dockerfile: ./docker/rest/Dockerfile
      target: local
      args:
        WORKDIR: ${WORK_DIR}
    ports:
      - "${REST_HOST_PORT}:${REST_CONTAINER_PORT}"
    volumes:
      - type: bind
        source: ./
        target: /go/app/src
    tty: true
    stdin_open: true
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - .env

  database:
    container_name: db
    image: postgres:13.6
    ports:
      - "${DB_HOST_PORT}:${DB_CONTAINER_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      TZ: Asia/Tokyo
    hostname: postgres
    user: ${DB_USER}

volumes:
  db_data:
    external: false